# Generated by Django 4.2.7 on 2023-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParlimentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliment_Assembly_Name', models.CharField(max_length=255, null=True)),
                ('state_Assembly_Name', models.CharField(max_length=255, null=True)),
                ('booth_Name', models.CharField(max_length=255, null=True)),
                ('Party_Name', models.CharField(max_length=255, null=True)),
                ('vote_Percentage', models.CharField(max_length=255, null=True)),
                ('total_Vote', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
