# Generated by Django 4.2.7 on 2024-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliment_Assembly_Name', models.CharField(max_length=255, null=True)),
                ('state_Assembly_Name', models.CharField(max_length=255, null=True)),
                ('booth_Name', models.CharField(max_length=255, null=True)),
                ('caste_name', models.CharField(max_length=255, null=True)),
                ('count', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
